### ISSUE TITLE
about the simulator

### ISSUE THREAD

**Issue by yygbruce** [SvrT31/Comparative_Analysis_of_PID_LQR_and_MPC_for_Drone_Stability_Under_Robot_Failure_Scenarios#1]
Hi, @SvrT31 ! Glad to see your open source project! How is the mujoco simulator? You don't need to start from writing the plugins. Recently, I am looking for information related to lqr and mpc,look forward to your update.

**Comment by SvrT31** [comment]
Hey yygbruce,

I tried using the Gazebo simulation environment. Specifically, Ignition
Garden with ROS2. That is where I got stuck.
We can use PX4 SITL and ArduCopter SITL but they don't give us any ability
to control rpm/thrust output of individual motors. Thus we can't check
LQR's or MPC's usability with them. So the only option left is to use
custom worlds and insert our own drone model in it.
We can take the model from PX4 SITL, but we will have to create our own
plugin. There are no premade plugins which will let us give inputs for
drone thrust generation. If you have good knowledge of making plugins, that
will take about 2 weeks of time. If you don't, then maybe a few months.

I have no idea about the mujoco simulator. Unreal engine might help (if you
know how to use it).

For LQR controller, you can check out this link -
https://automaticaddison.com/linear-quadratic-regulator-lqr-with-python-code-example/
For MPC controller, check this out (specifically for drones) -
https://www.instructables.com/Quadcopter-MPC-Control/

I am currently preparing for my semester exams, so there won't be any
updates till 12th Dec. I will keep updating the docx file after that.
Github will be updated once I am done with my thesis.

With Regards,
Suvrat Tembe

**Comment by yygbruce** [comment]
Ok, @SvrT31 !
